---
- name: 15 Configura kube-scheduler
  hosts: master-1
  remote_user: ubuntu
  gather_facts: false
  become: true

  vars:
    loadbalancer: "192.168.56.30"

  tasks:

    - name: Borra el fichero kube-scheduler.kubeconfig
      ansible.builtin.file:
        path: "/home/ubuntu/kube-scheduler.kubeconfig"
        state: absent

    - name: Primer comando con kubectl
      ansible.builtin.command: "kubectl config set-cluster kubernetes-the-hard-way \
                --certificate-authority=/var/lib/kubernetes/pki/ca.crt \
                --server=https://127.0.0.1:6443 \
                --kubeconfig=kube-scheduler.kubeconfig"
      args:
        chdir: /home/ubuntu
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Segundo comando con kubectl
      ansible.builtin.command: "kubectl config set-credentials system:kube-scheduler \
                --client-certificate=/var/lib/kubernetes/pki/kube-scheduler.crt \
                --client-key=/var/lib/kubernetes/pki/kube-scheduler.key \
                --kubeconfig=kube-scheduler.kubeconfig"
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task 2
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Tercer comando con kubectl
      ansible.builtin.command: "kubectl config set-context default \
                --cluster=kubernetes-the-hard-way \
                --user=system:kube-scheduler \
                --kubeconfig=kube-scheduler.kubeconfig"
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task 3
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Cuarto comando con kubectl
      ansible.builtin.command: "kubectl config use-context default \
                --kubeconfig=kube-scheduler.kubeconfig"
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task 4
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Cambio propietario, grupo y permisos del fichero admin.pem
      ansible.builtin.file:
        path: /home/ubuntu/kube-scheduler.kubeconfig
        owner: ubuntu
        group: ubuntu
        mode: '0740'
