---
- name: Crea el certificado de la CA raiz del cluster
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  become: true
  tasks:

    - name: Selecciona los ficheros de la carpeta ssl si existen
      ansible.builtin.find:
        paths: /home/ubuntu/ssl/
        patterns:
          - '*.crt'
          - '*.key'
          - '*.pem'
          - '*.csr'
      register: files_to_delete

    - name: Borra los ficheros de la carpeta ssl si existen
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Crea un directorio para los ficheros si no existe
      ansible.builtin.file:
        path: /home/ubuntu/ssl
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Genera una Key privada para la CA de 2048 bits con OpenSSL
      community.crypto.openssl_privatekey:
        path: /home/ubuntu/ssl/ca.pem
        size: 2048
    - name: Cambio propietario, grupo y permisos del fichero ca.pem
      ansible.builtin.file:
        path: /home/ubuntu/ssl/ca.pem
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    - name: Copia el fichero pem a key
      ansible.builtin.copy:
        src: /home/ubuntu/ssl/ca.pem
        dest: /home/ubuntu/ssl/ca.key
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera una solicitud de firma de certificado con OpenSSL
      community.crypto.openssl_csr:
        path: /home/ubuntu/ssl/ca.csr
        privatekey_path: /home/ubuntu/ssl/ca.pem
        subject: 'CN=KUBERNETES-CA, O=Kubernetes'
    - name: Cambio propietario, grupo y permisos del fichero ca.csr
      ansible.builtin.file:
        path: /home/ubuntu/ssl/ca.csr
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera un certificado CRT autofirmado con OpenSSL
      community.crypto.x509_certificate:
        path: /home/ubuntu/ssl/ca.crt
        privatekey_path: /home/ubuntu/ssl/ca.pem
        csr_path: /home/ubuntu/ssl/ca.csr
        provider: selfsigned
    - name: Cambio propietario, grupo y permisos del fichero ca.crt
      ansible.builtin.file:
        path: /home/ubuntu/ssl/ca.crt
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    - name: Copia el fichero pem a key
      ansible.builtin.copy:
        src: /home/ubuntu/ssl/ca.crt
        dest: /home/ubuntu/ca.crt
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: '0600'
