---
- name: 13 Configura kubect_config
  hosts: master-1
  remote_user: ubuntu
  gather_facts: false
  become: true

  vars:
    loadbalancer: "192.168.56.30"

  tasks:

    - name: Borra el fichero kube-proxy.kubeconfig
      ansible.builtin.file:
        path: "/home/ubuntu/kube-proxy.kubeconfig"
        state: absent
    - name: Borra el fichero kube-proxy.kubeconfig
      ansible.builtin.file:
        path: "/home/ubuntu/ssl/kube-proxy.kubeconfig"
        state: absent

    - name: Primer comando con kubectl
      ansible.builtin.command: "kubectl config set-cluster kubernetes-the-hard-way \
              --certificate-authority=/var/lib/kubernetes/pki/ca.crt \
              --server=https://{{ loadbalancer }}:6443 \
              --kubeconfig=kube-proxy.kubeconfig"
      args:
        chdir: /home/ubuntu/ssl
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Segundo comando con kubectl
      ansible.builtin.command: "kubectl config set-credentials system:kube-proxy \
                --client-certificate=/var/lib/kubernetes/pki/kube-proxy.crt \
                --client-key=/var/lib/kubernetes/pki/kube-proxy.key \
                --kubeconfig=kube-proxy.kubeconfig"
      args:
        chdir: /home/ubuntu/ssl
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task 2
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Tercer comando con kubectl
      ansible.builtin.command: "kubectl config set-context default \
                --cluster=kubernetes-the-hard-way \
                --user=system:kube-proxy \
                --kubeconfig=kube-proxy.kubeconfig"
      args:
        chdir: /home/ubuntu/ssl
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task 3
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Cuarto comando con kubectl
      ansible.builtin.command: "kubectl config use-context default \
                --kubeconfig=kube-proxy.kubeconfig"
      args:
        chdir: /home/ubuntu/ssl
      register: result
      changed_when: "'error' not in result.stdout"

    - name: Print return information from the previous task 4
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Cambio propietario, grupo y permisos del fichero kube-proxy.kubeconfig
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-proxy.kubeconfig
        owner: ubuntu
        group: ubuntu
        mode: '0740'

    - name: Mueve el fichero kube-proxy.kubeconfig
      ansible.builtin.copy:
        src: "/home/ubuntu/ssl/kube-proxy.kubeconfig"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: '0740'
        remote_src: true
