---
- name: 10 Crea el certificado para el cliente de API
  hosts: master-1
  remote_user: ubuntu
  gather_facts: false
  become: true
  tasks:

    - name: Genera el fichero service-account.key
      ansible.builtin.shell:
        cmd: openssl genrsa -out ./ssl/service-account.key 2048
        executable: /bin/bash
      register: result
      changed_when: "'error' not in result.stdout"
    - name: Cambio propietario, grupo y permisos del fichero service-account.key
      ansible.builtin.file:
        path: /home/ubuntu/ssl/service-account.key
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera el fichero service-account.csr
      ansible.builtin.shell:
        cmd: openssl req -new -key ./ssl/service-account.key -subj "/CN=service-accounts/O=Kubernetes" -out ./ssl/service-account.csr
        executable: /bin/bash
      register: result
      changed_when: "'error' not in result.stdout"
    - name: Cambio propietario, grupo y permisos del fichero service-account.csr
      ansible.builtin.file:
        path: /home/ubuntu/ssl/service-account.csr
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera el fichero service-account.crt
      ansible.builtin.shell:
        cmd: openssl x509 -req -in ./ssl/service-account.csr -CA ./ssl/ca.crt -CAkey ./ssl/ca.key -CAcreateserial  -out ./ssl/service-account.crt -days 1000
        executable: /bin/bash
      register: result
      changed_when: "'error' not in result.stdout"
    - name: Cambio propietario, grupo y permisos del fichero ca.crt
      ansible.builtin.file:
        path: /home/ubuntu/ssl/service-account.crt
        owner: ubuntu
        group: ubuntu
        mode: '0600'
