---
- name: 17 Copia los kubeconfig a los nodos segun necesidad de cada uno
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  become: true

  vars:
    listaficheros1: "{{ 'admin.kubeconfig kube-controller-manager.kubeconfig \
                kube-scheduler.kubeconfig kube-proxy.kubeconfig' | split }}"

    listaficheros2: "{{ 'admin.kubeconfig kube-controller-manager.kubeconfig kube-scheduler.kubeconfig' | split }}"


    listaficheros3: "{{ 'kube-proxy.kubeconfig' | split }}"

  tasks:

    - name: Copia los ficheros kubeconfig a la carpeta local
      ansible.builtin.fetch:
        src: "/home/ubuntu/{{ item }}"
        dest: ./temporal/
        flat: true
      when: inventory_hostname == "master-1"
      with_items: "{{ listaficheros1 }}"

    - name: Copia los ficheros kubeconfig al master-2
      ansible.builtin.copy:
        src: "./temporal/{{ item }}"
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      when: inventory_hostname == "master-2"
      with_items: "{{ listaficheros2 }}"

    - name: Copia los ficheros kubeconfig a los workers
      ansible.builtin.copy:
        src: "./temporal/{{ item }}"
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      when: inventory_hostname in groups['workers']
      with_items: "{{ listaficheros3 }}"
