---
- name: 28 Instala y lanza el CNI en los workers
  hosts: master-1
  remote_user: ubuntu
  gather_facts: false
  become: true

  vars:
    loadbalancer: "192.168.56.30"

  tasks:

    - name: Ejecuta comando kubectl para instalar el CNI
      ansible.builtin.command:
        cmd: kubectl apply -f "https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml"
      register: result
      changed_when: "'error' not in result.stdout"
      when: inventory_hostname == "master-1"
