---
- name: 05 Crea el certificado para el kube_proxy
  hosts: master-1
  remote_user: ubuntu
  gather_facts: false
  become: true
  tasks:

    - name: Genera el fichero kube-proxy.key
      ansible.builtin.shell:
        cmd: openssl genrsa -out ./ssl/kube-proxy.key 2048
        executable: /bin/bash
      register: result
      changed_when: "'error' not in result.stdout"
    - name: Cambio propietario, grupo y permisos del fichero kube-proxy.key
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-proxy.key
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera el fichero kube-proxy.csr
      ansible.builtin.shell:
        cmd: openssl req -new -key ./ssl/kube-proxy.key -subj "/CN=system:kube-proxy/O=system:node-proxier" -out ./ssl/kube-proxy.csr
        executable: /bin/bash
      register: result
      changed_when: "'error' not in result.stdout"
    - name: Cambio propietario, grupo y permisos del fichero kube-proxy.csr
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-proxy.csr
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera el fichero kube-proxy.crt
      ansible.builtin.shell:
        cmd: openssl x509 -req -in ./ssl/kube-proxy.csr -CA ./ssl/ca.crt -CAkey ./ssl/ca.key -CAcreateserial  -out ./ssl/kube-proxy.crt -days 1000
        executable: /bin/bash
      register: result
      changed_when: "'error' not in result.stdout"
    - name: Cambio propietario, grupo y permisos del fichero ca.crt
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-proxy.crt
        owner: ubuntu
        group: ubuntu
        mode: '0600'
