---
- name: Crea el certificado para el servidor de API
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  become: true
  tasks:

    - name: Genera una Key privada para clientes y servidores de 2048 bits con OpenSSL
      community.crypto.openssl_privatekey:
        path: /home/ubuntu/ssl/kube-apiserver.pem
        size: 2048
    - name: Cambio propietario, grupo y permisos del fichero kube-apiserver.pem
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-apiserver.pem
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/ubuntu/ssl/kube-apiserver.pem
        dest: /home/ubuntu/ssl/kube-apiserver.key
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera una solicitud de firma de certificado con OpenSSL
      community.crypto.openssl_csr:
        path: /home/ubuntu/ssl/kube-apiserver.csr
        privatekey_path: /home/ubuntu/ssl/kube-apiserver.pem
        subject: 'CN=kube-apiserver, O=Kubernetes'
        subject_alt_name: "DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster,\
                            DNS:kubernetes.default.svc.cluster.local,IP:172.16.0.1,IP:192.168.56.11,IP:192.168.56.12,IP:192.168.56.30,IP:127.0.0.1"
    - name: Cambio propietario, grupo y permisos del fichero kube-apiserver.csr
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-apiserver.csr
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Genera un certificado CRT con CA generada
      community.crypto.x509_certificate:
        path: /home/ubuntu/ssl/kube-apiserver.crt
        csr_path: /home/ubuntu/ssl/kube-apiserver.csr
        ownca_path: /home/ubuntu/ssl/ca.crt
        ownca_privatekey_path: /home/ubuntu/ssl/ca.pem
        provider: ownca
    - name: Cambio propietario, grupo y permisos del fichero ca.crt
      ansible.builtin.file:
        path: /home/ubuntu/ssl/kube-apiserver.crt
        owner: ubuntu
        group: ubuntu
        mode: '0600'
